name: PR checks
on: pull_request
env:
  SECRET_KEY: insecure_test_key

jobs:
  run-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build --tag ubuntu-com .

      - name: Run image
        run: |
          docker run --detach --publish 80:80 --env SECRET_KEY=insecure_secret_key
          sleep 1
          curl --head --fail --retry-delay 1 --retry 30 --retry-connrefused http://localhost
